// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Shos_TicTacToeML.Model
{
    public class ModelInput
    {
        [ColumnName("Stone1"), LoadColumn(0)]
        public float Stone1 { get; set; }


        [ColumnName("Stone2"), LoadColumn(1)]
        public float Stone2 { get; set; }


        [ColumnName("Stone3"), LoadColumn(2)]
        public float Stone3 { get; set; }


        [ColumnName("Stone4"), LoadColumn(3)]
        public float Stone4 { get; set; }


        [ColumnName("Stone5"), LoadColumn(4)]
        public float Stone5 { get; set; }


        [ColumnName("Stone6"), LoadColumn(5)]
        public float Stone6 { get; set; }


        [ColumnName("Stone7"), LoadColumn(6)]
        public float Stone7 { get; set; }


        [ColumnName("Stone8"), LoadColumn(7)]
        public float Stone8 { get; set; }


        [ColumnName("Stone9"), LoadColumn(8)]
        public float Stone9 { get; set; }


        [ColumnName("HasWon"), LoadColumn(9)]
        public bool HasWon { get; set; }


    }
}
