// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Shos_TicTacToeML.Model;

namespace Shos_TicTacToeML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Dropbox\Source\GitHub\Repos\Shos.TicTacToe\Shos.TicTacToe.GameRunner\data\gameresult2020.01.22.17.22.00.csv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual HasWon with predicted HasWon from sample data...\n\n");
            Console.WriteLine($"Stone1: {sampleData.Stone1}");
            Console.WriteLine($"Stone2: {sampleData.Stone2}");
            Console.WriteLine($"Stone3: {sampleData.Stone3}");
            Console.WriteLine($"Stone4: {sampleData.Stone4}");
            Console.WriteLine($"Stone5: {sampleData.Stone5}");
            Console.WriteLine($"Stone6: {sampleData.Stone6}");
            Console.WriteLine($"Stone7: {sampleData.Stone7}");
            Console.WriteLine($"Stone8: {sampleData.Stone8}");
            Console.WriteLine($"Stone9: {sampleData.Stone9}");
            Console.WriteLine($"\n\nActual HasWon: {sampleData.HasWon} \nPredicted HasWon: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
